In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('/content/drive/MyDrive/ML/Project/survey_results_public v1.csv')

In [4]:
Needed_data = data[['WorkExp','ConvertedCompYearly','ICorPM']]

In [5]:
Needed_data.drop(Needed_data[Needed_data["WorkExp"].isnull()==True].index, axis = 0, inplace = True)
Needed_data.drop(Needed_data[Needed_data["ConvertedCompYearly"].isnull()==True].index, axis = 0, inplace = True)
Needed_data.drop(Needed_data[Needed_data["ICorPM"].isnull()==True].index, axis = 0, inplace = True)

<ipython-input-5-91026515bcc7>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Needed_data.drop(Needed_data[Needed_data["WorkExp"].isnull()==True].index, axis = 0, inplace = True)
<ipython-input-5-91026515bcc7>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Needed_data.drop(Needed_data[Needed_data["ConvertedCompYearly"].isnull()==True].index, axis = 0, inplace = True)
<ipython-input-5-91026515bcc7>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-v

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
d = {}
for j in Needed_data[['ICorPM']]:
    Needed_data[j] = le.fit_transform(Needed_data[j])
    d[j] = le.classes_

<ipython-input-12-bf1234e31426>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Needed_data[j] = le.fit_transform(Needed_data[j])


Variable d stores labelled data which is converted into numeric using LabelEncoding

In [ ]:
d

{'ICorPM': array(['Independent contributor', 'People manager'], dtype=object)}

In [ ]:
d1 = {}
for j in Needed_data[['ICorPM']]:
    Needed_data[j] = le.fit_transform(Needed_data[j])
    d1[j] = le.classes_

<ipython-input-14-d0fb9be8cc22>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Needed_data[j] = le.fit_transform(Needed_data[j])


Converted labelled data into numeric form

In [ ]:
d1

{'ICorPM': array([0, 1])}

In [ ]:
Needed_data[['ICorPM']] = Needed_data[['ICorPM']].apply(le.fit_transform)

<ipython-input-16-177bc324f577>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Needed_data[['ICorPM']] = Needed_data[['ICorPM']].apply(le.fit_transform)


In [ ]:
Needed_data

WorkExp  ConvertedCompYearly  ICorPM
8          6.0              49056.0       0
11        14.0             194400.0       1
12         5.0              65000.0       0
14         5.0             110000.0       0
21         4.0              34126.0       0
...        ...                  ...     ...
73112      3.0              52255.0       1
73113      7.0              94000.0       0
73116     16.0             115000.0       0
73119      9.0              70000.0       0
73120      2.0              35192.0       0

[26564 rows x 3 columns]

In [ ]:
X = Needed_data[['WorkExp','ConvertedCompYearly']]
y = Needed_data[['ICorPM']]

## Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr = LogisticRegression()

In [ ]:
lr.fit(X,y)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [ ]:
y_pred = lr.predict(X)

In [ ]:
X.shape

(26564, 2)

In [ ]:
lr.predict_proba(X)

array([[0.65347952, 0.34652048],
       [0.81739585, 0.18260415],
       [0.63217683, 0.36782317],
       ...,
       [0.84066236, 0.15933764],
       [0.71981152, 0.28018848],
       [0.55686443, 0.44313557]])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
acc = accuracy_score(y,y_pred)

In [ ]:
print(acc)

0.8510766450835717


## SVM - (Support Vector Machine)

In [ ]:
# Data preprocessing
Needed_data = data[['WorkExp','ConvertedCompYearly','ICorPM']]

#------
Needed_data.drop(Needed_data[Needed_data["WorkExp"].isnull()==True].index, axis = 0, inplace = True)
Needed_data.drop(Needed_data[Needed_data["ConvertedCompYearly"].isnull()==True].index, axis = 0, inplace = True)
Needed_data.drop(Needed_data[Needed_data["ICorPM"].isnull()==True].index, axis = 0, inplace = True)

#Extracting Independent and dependent Variable  
x= Needed_data[['WorkExp','ConvertedCompYearly']].values  
y= Needed_data[['ICorPM']].values  
  
# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)  
#feature Scaling  
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)       

<ipython-input-12-1ba4c594370c>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Needed_data.drop(Needed_data[Needed_data["WorkExp"].isnull()==True].index, axis = 0, inplace = True)
<ipython-input-12-1ba4c594370c>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Needed_data.drop(Needed_data[Needed_data["ConvertedCompYearly"].isnull()==True].index, axis = 0, inplace = True)
<ipython-input-12-1ba4c594370c>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-vie

In [ ]:
from sklearn.svm import SVC # "Support vector classifier"  
classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(x_train, y_train)  

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear', random_state=0)

In [ ]:
#Predicting the test set result  
y_pred= classifier.predict(x_test)  

In [ ]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)  

In [ ]:
cm

array([[5643,    0],
       [ 998,    0]])

In [16]:
import numpy as nm
import matplotlib.pyplot as mtp  

## Decision Tree

In [6]:
#Extracting Independent and dependent Variable  
x= Needed_data[['WorkExp','ConvertedCompYearly']].values  
y= Needed_data[['ICorPM']].values   
  
# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)  
  
#feature Scaling  
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()  
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)    

In [8]:
#Fitting Decision Tree classifier to the training set  
from sklearn.tree import DecisionTreeClassifier  
classifier= DecisionTreeClassifier(criterion='entropy', random_state=0)  
classifier.fit(x_train, y_train)  

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [9]:
#Predicting the test set result  
y_pred= classifier.predict(x_test)  

In [10]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)  

In [11]:
cm

array([[5043,  600],
       [ 856,  142]])

## Random Forest

In [19]:
#Extracting Independent and dependent Variable  
x= Needed_data[['WorkExp','ConvertedCompYearly']].values  
y= Needed_data[['ICorPM']].values    
  
# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)  
  
#feature Scaling  
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)    

In [20]:
#Fitting Decision Tree classifier to the training set  
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 10, criterion="entropy")  
classifier.fit(x_train, y_train)

<ipython-input-20-76efe3f81bf7>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(x_train, y_train)


RandomForestClassifier(criterion='entropy', n_estimators=10)

In [21]:
#Predicting the test set result  
y_pred= classifier.predict(x_test)  

In [22]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)  

In [23]:
cm

array([[5129,  514],
       [ 861,  137]])

## Naive Bayes

In [24]:
x= Needed_data[['WorkExp','ConvertedCompYearly']].values  
y= Needed_data[['ICorPM']].values 
  
# Splitting the dataset into the Training set and Test set  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)  
  
# Feature Scaling  
from sklearn.preprocessing import StandardScaler  
sc = StandardScaler()  
x_train = sc.fit_transform(x_train)  
x_test = sc.transform(x_test)  

In [25]:
# Fitting Naive Bayes to the Training set  
from sklearn.naive_bayes import GaussianNB  
classifier = GaussianNB()  
classifier.fit(x_train, y_train)  

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [26]:
# Predicting the Test set results  
y_pred = classifier.predict(x_test)  

In [27]:
#Making the Confusion Matrix  
from sklearn.metrics import confusion_matrix  
cm = confusion_matrix(y_test, y_pred)  

In [28]:
cm

array([[5624,   19],
       [ 997,    1]])